### ISSUE TITLE
KC-135 and Certain RHS vehicles not loading

### ISSUE THREAD

**Issue by CrazyStryker** [Fullerpj/United-States-Air-Force-Mod#100]
It seems I cannot get inside the KC-135 from the outside and RHS tanks and other vehicles will not load into the C-5 and C-17.

**Comment by mgkid3310** [comment]
Must pe action position problem. I solved it by using a car as a ladder and park it next to the cockpit. Maybe a ladder vehicle should be added

ps. E-3 still has the same problem, but not solved

**Comment by Fullerpj** [comment]
Already fixed
