### ISSUE TITLE
Licens

### ISSUE THREAD

**Issue by XeonDiaboli** [Fullerpj/United-States-Air-Force-Mod#101]
I have a question to the licen. in the Armaholic is the Mod with the only personaly licen and only entertainment.
I want to have the mod on a Server over the steam workshop. 
It is possible to change the licens or that you upload this great mod to Steam workshop?

**Comment by Fullerpj** [comment]
No the current mod is not allowed on the steam workshop, the update however
will be

**Comment by XeonDiaboli** [comment]
give it single mods on steam?

**Comment by Fullerpj** [comment]
What?

**Comment by XeonDiaboli** [comment]
sroory, give it single plans from the mod on steam

**Comment by Fullerpj** [comment]
Thanks bye see you at the release
