### ISSUE TITLE
not downloading from armaholic 

### ISSUE THREAD

**Issue by MertYildiz** [Fullerpj/United-States-Air-Force-Mod#102]
Hello, i cant download your mod from armaholic website. My problem is, whenever i try to download it, it lets me download 1 or 2 mb and then it shows me as complete and when i try to open it, it tells me the archive is corrupted. What can i do about it? Thanks in advance.

**Comment by Fullerpj** [comment]
You need to speak with foxhound on the forums.

**Comment by MertYildiz** [comment]
sorry what is foxhound ?
