### ISSUE TITLE
AC-130 bugging

### ISSUE THREAD

**Issue by Finswgman** [Fullerpj/United-States-Air-Force-Mod#103]
Everytime i try to fly the ac-130 it starts to bounce up and because of that i lose speed and cant get in the air, this doesnt happen with other aircraft only with the ac-130 and also the b2 doesnt make any sound and when i set the b2 so that it carries nukes, the nukes wont appear. This is the first time it happens

**Comment by Ares513** [comment]
I'm also having this issue

**Comment by MartieTheSmartie** [comment]
Same here...
