### ISSUE TITLE
AC-130, osprey(armed) clipping, AI in stratotanker is retarded and the rescue hawk is difficult to enter, and stability and a lack of a HUD or any targeting with the b-1 and b2

### ISSUE THREAD

**Issue by ImmortalPhoenix159** [Fullerpj/United-States-Air-Force-Mod#104]
AC-130, osprey(armed) clipping, AI in stratotanker is retarded and the rescue hawk is difficult to enter, and stability and a lack of a HUD or any targeting with the b-1 and b2,   (EDIT)   f35 causes any entity to turn to civilian. all as mentioned above my unit use this mod and has caused a fair few issues as most of the aircraft we want to use we cant because of the listed issues if a fix could be made it would be much appreciated

**Comment by Fullerpj** [comment]
Please read the forum. Thanks. Everything you listed is fixed in the update.
