### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by mFaunda** [Fullerpj/United-States-Air-Force-Mod#105]
Closed

**Comment by Fullerpj** [comment]
Don’t bother trying or getting others to work on this. We have fixed these issues already. Please read the forum. Thank you

**Comment by mFaunda** [comment]
The BH forums only say it goes up to version 0.5.3, which is the version I downloaded yesterday.  I'm sorry but I don't know what other forum to look for.

**Comment by Fullerpj** [comment]
I meant read the thread.
