### ISSUE TITLE
[Suggestion] Add class-names to the wiki

### ISSUE THREAD

**Issue by davidcit646** [Fullerpj/United-States-Air-Force-Mod#109]
It might be a good idea to, when talking about munitions or aircraft, to also include the object's class-names. Doing so would allow mission makers, such as myself, to more easily identify certain systems, thus making working with them much easier.

**Comment by RaynorD** [comment]
Would a page that lists the classnames for everything work?

**Comment by davidcit646** [comment]
Yes it would. It would help immensely.

**Comment by RaynorD** [comment]
Generated a classnames page from the config, does this do what you need?
https://github.com/Fullerpj/United-States-Air-Force-Mod/wiki/Weapon-Classnames
