### ISSUE TITLE
(BUG) Target Boxes Not Appearing Through Camera

### ISSUE THREAD

**Issue by Prototype9x** [Fullerpj/United-States-Air-Force-Mod#110]
When looking at Vehicles through targeting camera, the white square does not appear around vehicles. Making target acquisition nearly impossible unless you are flying towards the target. The white squares show up around target when flying TOWARDS it. Then the white boxes appear on the HUD. Before the USAF Mod this was not the case and we are unsure if this is how it's supposed to be. Just reporting what we found.

**Comment by RaynorD** [comment]
Yes this is intended behavior. Magic contact squares are not a thing in the real TGP. Appreciate all your feedback,
