### ISSUE TITLE
AGM-65D Not Locking On

### ISSUE THREAD

**Issue by Prototype9x** [Fullerpj/United-States-Air-Force-Mod#111]
AGM-65D (IR) Missiles not locking on to vehicles. Vehicles show up as "HOT" through Thermals. Does the Engine have to be on? We had the SAM sites firing numerous missiles. We thought the targets were hot.

**Comment by RaynorD** [comment]
Yes this is a dumb behavior of the SAM vehicles not being engine on but still able to fire missiles. We'll see if we can find a good solution.

**Comment by RaynorD** [comment]
Will be fixed in 1.0.6.1.
