### ISSUE TITLE
A-10 Pain Points 

### ISSUE THREAD

**Issue by Prototype9x** [Fullerpj/United-States-Air-Force-Mod#112]
B/2/A/1-7 SP on 01/18/2020, a couple of things they noted and wanted me to share with you.

-Napalm didnt napalm
-A-10's cant carry bunker busters
-It flies like a thicc jetski (too sluggish)
-Controls are spongey and flaccid

Unsure if we should classify this as a bug? I would agree that the flight model is a lot different than FIR however that's to be expected.

**Comment by RaynorD** [comment]
- Will check on napalm, unsure of its status
- Which bunker buster are you referring to? If it's the 28, it's too heavy to carry IRL.
- Flight model was tuned to be similar to DCS with a medium payload. Slightly more maneuverable than the vanilla A-164 but still a heavy feel. It's not a fighter jet, it's a gun with wings.
