### ISSUE TITLE
A-10 MFD's Not Working

### ISSUE THREAD

**Issue by Prototype9x** [Fullerpj/United-States-Air-Force-Mod#113]
![20200126200132_1](https://user-images.githubusercontent.com/56491899/73144752-e4f80700-4076-11ea-932d-c43caf1a77f1.jpg)

A-10 MFD's not displaying any information.

**Comment by RaynorD** [comment]
What steps leds to this?

**Comment by ghost** [comment]
> What steps leds to this?

I encountered this issue as well. I spawned mine in editor and in zeus both spawn with white MFD's.
