### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by AlphaKilo07** [Fullerpj/United-States-Air-Force-Mod#13]
Coppied from front page

**_Aircraft Assets_**
**Bomber**
- [ ] B-1 Bomber
- [ ] B-2 Spirit NEW!!!

**Fighters**
- [ ] F-16C Fighting Falcon
- [ ] F/A-22 Raptor
- [ ] F-35A Joint Strike FIghter

**Transports/Support**
- [ ] C-5 Galaxy
- [ ] C-17 Globemaster III
- [ ] CV-22 Osprey
- [ ] C-130J Super Hercules
- [ ] KC-135 StratoTanker
- [ ] MC-130J Commando II

**Rotary**
- [ ] HH-60G PaveHawk
- [ ] HH-60 Rescue Hawk

**Recon/Early Warning**
- [ ] E-3 AWACS NEW!!!
- [ ] MQ-9 Reaper

**Close Air Support**
- [ ] AC-130U Gunship
- [ ] A-10C Warthog
- [ ] RQ-4A Global Hawk

**Units**
- [ ] Air Force Special Operations (AFSOC)
- [ ] Department of the Air Force Officers
- [ ] 811th Expeditionary Security Forces Squadron

**_FEATURES_**
- [ ] Aerial Refueling
- [ ] Nuclear Assets
- [ ] Service Menus
- [ ] Multiple Weapons
- [ ] GPS/INS Systems for applicable Aircraft
- [ ] UAV Systems for Recon
- [ ] Ejection Seats (Nxt Update Guaranteed)
- [ ] Avionics for ECM Pods, HARM, and Targeting Pods (Nxt Update Guaranteed)
- [ ] Working MFDs
- [ ] More bombs!!!

**Comment by AlphaKilo07** [comment]
Pages for all aircraft and home made, not complete.

**Comment by rlex** [comment]
https://community.bistudio.com/wiki/USAF_Mod maybe just extend existing?

**Comment by AlphaKilo07** [comment]
@rlex I think I may just copy from there and add to this rather. :smiley:
