### ISSUE TITLE
Cannot put BFV in C-17

### ISSUE THREAD

**Issue by AlphaKilo07** [Fullerpj/United-States-Air-Force-Mod#15]
Attempted to but BFV (Bradley Fighting Vehicle) but said it was too large. Not sure what the cause is. The RHS Abrams fits but the Bradley doesn't.

**Comment by Fullerpj** [comment]
Your trying to put that in C-17 or C130? you kinda combined the two in your title

**Comment by AlphaKilo07** [comment]
C-17, had a typo :laughing:

**Comment by Fullerpj** [comment]
Hmm you should be able to get a BFV in there. Try the C5 its for that purpose anyway. If it does it on that one we have a issue. Also please remember to use the labels

**Comment by AlphaKilo07** [comment]
We cannot assign labels, in addition I've been looking into this for paradropping the BFV. Thanks for your help though :heart:

**Comment by Diesel486** [comment]
update for you. cannot put bradley's into the c-5. my guess is they are too tall, m1 mbt's are a fair bit shorter. havnt checked the c-17

**Comment by Fullerpj** [comment]
Are these RHS vehicles?

**Comment by Diesel486** [comment]
bradleys i tested is rhs
