### ISSUE TITLE
AC-130 autopilot kills not counted in statistics

### ISSUE THREAD

**Issue by rlex** [Fullerpj/United-States-Air-Force-Mod#17]
1) Kill some enemies while in autopilot (new) mode
2) They're not counted in stats

**Comment by Fullerpj** [comment]
will look into it but not high on my priority list..mainly looking for bugs

**Comment by randomslap** [comment]
I believe the kills go to the AI pilot after you enter autopilot. An AI pilot is placed after entering autopilot. It is like the other vehicles where the pilot or driver takes credit of the gunner's kills. There isn't an option to fix this.
