### ISSUE TITLE
Planes JIP issue

### ISSUE THREAD

**Issue by rlex** [Fullerpj/United-States-Air-Force-Mod#23]
Not sure if this USAF issue, but...

1) Join server. Spawn plane, ie B-2.
2) Disconnect
3) Reconnect. Now you can't enter B-2 or damage it (simulation stopped?)

My mission was written using ALiVE mod so i really can't test it without ALiVE. 

I tested it with RHS and vanilla A3 planes, and this is not happening with them.

**Comment by Fullerpj** [comment]
Not our issue
