### ISSUE TITLE
Lower-case PBO names (linux DS compat)

### ISSUE THREAD

**Issue by rlex** [Fullerpj/United-States-Air-Force-Mod#24]
Remember #23? I traced issue.
I installed USAF on our secondary server (linux), and discovered AC-130 have no "new" autopilot.
After some messing i traced the problem - filenames is wrong on linux case-sensitive filesystem.
Renaming all to lowercase helped, and USAF now works great, and most of problems is gone.

It's a well-known issue: 
http://erictgrubaugh.com/play/games/arma/installation-and-configuration-of-an-arma-3-linux-dedicated-server/
http://forums.bistudio.com/showthread.php?173055-Problem-with-mods-when-launching-arma-3-server-on-linux-dedicated-server/page2
http://www.armaholic.com/forums.php?m=posts&q=24934

**Comment by Fullerpj** [comment]
not my concern
