### ISSUE TITLE
C-17 (probably C-5 too) ramp sound 

### ISSUE THREAD

**Issue by rlex** [Fullerpj/United-States-Air-Force-Mod#25]
Tiny bug:
When opening/closing C17 ramp, you can hear "clicking" at the end of sound, like the one when you power on / power off mic. Should be pretty easy to fix, just cut "silence" with clicking near the end of sound.

**Comment by rlex** [comment]
yeah, c-5 is also affected, seems they use same sounds

**Comment by Fullerpj** [comment]
nitpick issue

**Comment by rlex** [comment]
Can i just send you fixed sound?

**Comment by Fullerpj** [comment]
if you feel the need....
