### ISSUE TITLE
Static paradrop issue

### ISSUE THREAD

**Issue by rlex** [Fullerpj/United-States-Air-Force-Mod#27]
1) Be a pilot of C-17
2) Fly around
3) Use paradrop from menu. Nothing happens. Well i am a pilot, why should i paradrop...
4) Land C-17, i used autopilot, doubt that even matters
5) Try to exit C-17 when on ground and fully stopped
6) You got paradropped from position where you used paradrop in menu

Observed in MP. Have not tested HALO jumps yet.

**Comment by Fullerpj** [comment]
will look into issue..paradrop will be disabled until further notice

**Comment by Fullerpj** [comment]
Fixed by adding in new script. Paradrop script obsolete
