### ISSUE TITLE
A-10C Secondary Hydra pod empty

### ISSUE THREAD

**Issue by rlex** [Fullerpj/United-States-Air-Force-Mod#29]
(I swear you'll kill me soon :D)
1) Place A-10 and ammo truck
2) Open service menu
3) Put 2 Hydra 7 pods, one on each side
4) Now, cycling weapons, you'll see ordinary Hydra 70 AP rockets, and other "Hydra 70 AWCKS" or something like this, which is empty and cannot be fired.

**Comment by Fullerpj** [comment]
Im aware of this..working to resolve the issue
