### ISSUE TITLE
landing gear

### ISSUE THREAD

**Issue by nextjr** [Fullerpj/United-States-Air-Force-Mod#33]
when using the AC-130 specter the landing gear bugs out on all usaf aircraft for the rest of the game session.

**Comment by Fullerpj** [comment]
i need a picture of this or something..i have never had this and what do you mean bugs out

**Comment by nextjr** [comment]
the landing gear stays out, it is still useable but will not retract, even after leaving and re-entering vehicle happens on all other spawned usaf vehicles.

**Comment by Fullerpj** [comment]
What are you using to spawn them?

**Comment by nextjr** [comment]
virtual armory.

**Comment by Fullerpj** [comment]
i have yet to work on Virtual Armory..spawn them the normal way for now

**Comment by nextjr** [comment]
hows that?

**Comment by Fullerpj** [comment]
just spawn them empty in editor..without using virtual armory.

**Comment by nextjr** [comment]
oh alright.

**Comment by rlex** [comment]
I noticed that too, but the issue is that is not affecting only USAF mod, but all modded planes. I had that issues with RHS too, at some point of time ALL gear on ALL modded aircrafts stops working. I feel like this is arma engine issue...
