### ISSUE TITLE
OSPREY Engine power

### ISSUE THREAD

**Issue by olanguedoc** [Fullerpj/United-States-Air-Force-Mod#34]
Nice mod pack. 

Noticed something weird with the osprey in VTL & airplane mode.

I am using a Joystick + throttle combo. It seems the power course run from 90 to 100% on the throttle instead of 0 to 100%. So when i put 90% throttle... the osprey is at idle. It is very hard to manage the power. 

In Airplane mode it is the same. I think there might be something to look oever there... if not... what an amazing upgrade to the first osprey port. Wow.

**Comment by RDIXON9** [comment]
Are you using analog input for the control settings?

**Comment by Fullerpj** [comment]
idk if thats a mod problem brother.

**Comment by olanguedoc** [comment]
Pretty sure it is. I use analog controls. Real throttle etc. No issue with any of the other Planes in the pack.
