### ISSUE TITLE
Osprey Ejection positon

### ISSUE THREAD

**Issue by olanguedoc** [Fullerpj/United-States-Air-Force-Mod#36]
It is currently impossible for passenger to eject for the Osprey in flight with the back door opened. 
The eject position is to close from the hull. 

It would be nice move it a little.

**Comment by RDIXON9** [comment]
I have a script for haloing that works for passengers if you would like it I would share.

**Comment by olanguedoc** [comment]
Yes plz.

I would love to have it. Nice work on your mod pack. Very nice work.

Did you see my post about the power distribution in the osprey compared To other airrcraft? Was I clear in my explaination?

Olivier Languedoc
Réalisateur @ La Cavalerie
514.991.5052

**Comment by RDIXON9** [comment]
I am not part of USAF team, I saw this post and have a possible fix to your issue. What is your email, I can send you a small mission to see if you would like to use what I have.

**Comment by olanguedoc** [comment]
Is it a script that makes the unit invulnerable for a couple of seconds using a trigger ? 

My e-mail is olanguedoc@gmail.com

Olivier Languedoc
Réalisateur @ La Cavalerie
514.991.5052

**Comment by RDIXON9** [comment]
I sent an email however here is the DBox link for anyone else just follow the  directions in  the notepad doc 

https://www.dropbox.com/s/pt26ea0yzrarmgn/HALO_TEST.VR.7z?dl=0

**Comment by Fullerpj** [comment]
You can now walk in the osprey no more need for scripts
