### ISSUE TITLE
Osprey bugs

### ISSUE THREAD

**Issue by Coren4** [Fullerpj/United-States-Air-Force-Mod#39]
-bulletproof cockpit
-can't be locked with ground AA rockets
-should to have radar when it is locked with rockets
-explode when someone is inside plane, but just standing(not sitting on bench) on floor - when moving plane

Should i post each bug seperatly, or can i post it together for each machine?

**Comment by Fullerpj** [comment]
Fixed the AA rockets lock and fixed the Radar. 
Cant reproduce the explosion mentioned.
Cockpit can now be shot to hell

**Comment by Coren4** [comment]
Awesome thank you:)
