### ISSUE TITLE
A-10C AGM-65 Proxies Mispositioned (Stations 30-35)

### ISSUE THREAD

**Issue by RaynorD** [Fullerpj/United-States-Air-Force-Mod#46]
Currently: http://i.imgur.com/r6FdgQ1.jpg
Reference: http://www.globalsecurity.org/military/systems/aircraft/systems/images/lau-88-DD-SD-00-02602.jpg

**Comment by RaynorD** [comment]
Also just noticed that the side missiles are not rotated correctly, about 30 degrees downward.

**Comment by Fullerpj** [comment]
Fixed
