### ISSUE TITLE
Very limited options in A-10C loadout editor dropdowns

### ISSUE THREAD

**Issue by RaynorD** [Fullerpj/United-States-Air-Force-Mod#47]
No JDAMs of any kind, no GBU-12 x3, no AGM-65 x3, and no options at all for station 6 (center).

**Comment by Fullerpj** [comment]
this is a nit pick issue not a issue in need of fixing. I intended to put JDAMS on there and i still do just not at this time. The Station 6 i have something planned for..so its ok if nothing is there for now.

**Comment by RaynorD** [comment]
I understand you're short on time, working on the whole pack. Would you like me to edit the function to add realistic hardpoints? I've already opened it up and got a GBU-12 on the center hardpoint. I'm a DCS player as well, and this is my favorite craft in the pack, and JDAMs are my munition of choice. I'm the developer of the A3 Mod Preset Launcher, so I'm comfortable with code.

**Comment by Fullerpj** [comment]
What's your steam name? We can talk on there

**Comment by RaynorD** [comment]
(snip)
