### ISSUE TITLE
F-22 Loadout Script Problem After Equipping GBU-31s

### ISSUE THREAD

**Issue by RaynorD** [Fullerpj/United-States-Air-Force-Mod#49]
On the F-22, when rearming in any way after having equipped GBU-31s with the custom loadout editor, the script goes very wrong: http://i.imgur.com/xwW42Jx.jpg
Looks like a station offset going wrong somewhere, going to take a look at the script.

**Comment by RaynorD** [comment]
Forgot to mention, no script errors are thrown.

**Comment by Fullerpj** [comment]
looking into this one now

**Comment by Fullerpj** [comment]
I see what you did you loaded everything that was available onto the F22. Im trying to learn restrictions but basically you ran out of proxies. If your going to load the 8 SDBs do not load the JDAMS..if your not going to load the 8 SDBs feel free to load the JDAMS. If you load the AIM-10s thats fine also..load the Jdams if you please.

**Comment by RaynorD** [comment]
Ah, ok. That wasn't clear from the design of the loadout editor. If I understand correctly, it would make more sense to have only two dropdowns for the center bay, with 1x 31, 1x 32, and 4 SDBs each.
