### ISSUE TITLE
F35 Afterburner Bug

### ISSUE THREAD

**Issue by Octop01** [Fullerpj/United-States-Air-Force-Mod#51]
When activating Afterburner it considerably decreases maneuverability and leads to awkward physics. Also when reaching speeds of 1300 km/h the plane loses altitude automatically.

**Comment by Fullerpj** [comment]
Your not going to be using afterburner in a dog fight...the afterburner script is not mine talk to john Spartan

**Comment by Octop01** [comment]
The problem is that the F35 is the only jet that currently has this bug. As far as i know, this has something to do with the Physx simulation of the USAF F35, which is partly based upon the FC-37 Thunder which reportedly had problems like blowing up on the nimitz,so probably this causes the problem. John already managed to solve this problem on the black wasp.

**Comment by Fullerpj** [comment]
I will look into this tonite. The F35A I didn't remove the physx but I will I did for the F35c

**Comment by Octop01** [comment]
Problem seemingly not existing as of hotfix v0.5.1, considering it as fixed
