### ISSUE TITLE
Underpowered missiles

### ISSUE THREAD

**Issue by Octop01** [Fullerpj/United-States-Air-Force-Mod#52]
When compared to "ordinary" missles used by other jet mods, the USAF missiles seem way to slow and are to easy to evade, thus leading to significant problems during air to air combat.

**Comment by Fullerpj** [comment]
I'll look into this..I don't have any issues and seems like your just comparing and complaining.

**Comment by Octop01** [comment]
Glad to hear that. And please don't take this as offense, i want to objectivly help you developing your mod and by no means attack you.

**Comment by Fullerpj** [comment]
Sorry I went off on you. Was having a bad day here at training

**Comment by Octop01** [comment]
No Problem bro :). I wish you good luck with your further training.

**Comment by Octop01** [comment]
So i tested again for some time now and i would propose to make the Aim-120s perform just like Ollis in terms of speed and damage. I can post some comparasion videos about the performance of missiles in some popular jet mods if you want.
