### ISSUE TITLE
F35 GBU-53 and GAU-22/A not effective

### ISSUE THREAD

**Issue by Octop01** [Fullerpj/United-States-Air-Force-Mod#53]
As far as i have noticed, the F35 still uses some weapons of Ollis "FC-37 Thunder", namely the GAU/22A and GBU-53. While i am aware that this is probaly subject to change the current issues are:
The GAU/22 does not use APEX rounds which also explode and has a low rate of fire, the GBU-53 SDB needs atleast two hits to destroy targes like the T-100 Varsuk, is not accurate enough against ground targets(especially moving ones) and is easily confused by smoke, although the targets shouldn't be able to be warned at all to effectivly deploy countermeasures. I would suggest making the GBU-53 one hit kills against Tanks, just like the GBU-39 of the raptor.

**Comment by Fullerpj** [comment]
Raise the damage got it... Arma 3 is not going to simulate everything perfectly keep that in mind...

**Comment by Octop01** [comment]
Also, when the gear is down, the GAU/22 is disabled and has 0 rounds in it. This is probably due to the fact that the FC-37 used a gundpod, which of course would fire on the own gear then.

**Comment by Fullerpj** [comment]
I left it like that. Not gonna fire at base right?

**Comment by Octop01** [comment]
Haha ok.

**Comment by Octop01** [comment]
With the new update the GAU/22A does proper work now. However the GBU-53s are still extremly ineffective against tanks etc, considering damage and accuracy.

**Comment by Octop01** [comment]
[Update] Damage of GBU-53 fixed as of hotfix v0.5.1however, inaccuracy still makes it ineffective.
