### ISSUE TITLE
F35 Display Bug

### ISSUE THREAD

**Issue by Octop01** [Fullerpj/United-States-Air-Force-Mod#54]
This is a minor bug i noticed. While using the menu to chose your loadout on one side it show 2x GBU-12 while on the other it properly shows only one bomb.

http://images.akamai.steamusercontent.com/ugc/6184914226285516371/A420D8D9CF06E82C57DBC03AF86ECDD6D5EBC32D/

**Comment by Fullerpj** [comment]
Fixed already
