### ISSUE TITLE
Cv-22 auto-hover issue

### ISSUE THREAD

**Issue by crazyta** [Fullerpj/United-States-Air-Force-Mod#55]
Fullerpj,

So im havingan odd issue with the osprey.  I can vertically take off, put the gear up and transition to semi forward flt then turn off auto hover and go to full forward flight. No issues there however when i try to land i cant get it to go to hover. Tried it with joystick/throttle and also keyboard only. Same issue both times. I have literally stalled it over the runway with auto-hover on and gear down but the nacelles still stuck in full forward flight mode. Thoughts?

**Comment by Fullerpj** [comment]
I'll have to try to recreate it. I have never had a issue like this with the osprey

**Comment by crazyta** [comment]
Roger. So i just did some more testing based on some of your other posts.  "Z" has to be pressed and held in order to put the nacelles into vertical mode.  That works (i was not holding z down). I keep however getting stuck with the gear down and not responding which also keeps the nacelles from going to "slightly forward" mode.  To reconstruct try taking off, transitioning then landing and trying again all while cycling gear up and down

**Comment by crazyta** [comment]
So had an interesting test last night.  Both digital and analog controls are required for cv-22 landing and must be used separately when mapping to joystick/throttle.   Again after 2-3 rapid ingress/egress approaches to a target the gear became stuck in the "down" position however tapping the gear button caused the nacelles to rotate forward 15 degrees each time making for better egress transition to forward flight. Gear was still down but the effect was good
