### ISSUE TITLE
Server desync linked to some aircraft.

### ISSUE THREAD

**Issue by Tibet4690** [Fullerpj/United-States-Air-Force-Mod#60]
When certain aircraft are used server desync spikes off the chart, readings top out at a consistent 100,000. (This is no exaggeration)

Problem Aircraft:
F-22
F-35A
C-17
B-2

The rest of your awesome aircraft work without desync issues.

Given that these issues have only occurred / been replicated with certain aircraft I am inclined to suggest this maybe a script issue?... but I am no expert on the subject.

All tests were done on a dedicated server with only four players and no AI spawned so this isn't due to server load either.

Hopefully this helps pinpoint the issue, if you need any additional info I would be happy to provide it as well.

**Comment by Tibet4690** [comment]
Update: So I've been doing some more testing with the F-22 and it appears the problems are linked to headless clients. Once all headless clients are disconnected the desync issue disappears, but again this only occurs with specific aircraft from your pack.

I utilize the werthles headless client script on my server: http://steamcommunity.com/sharedfiles/filedetails/?id=459317544

As mentioned previously I am no expert as such I am perplexed as to why these issues are occurring... let alone occuring with player controlled vehicles well the HCs only handle AI calculations. I'll continue trying to research this myself, but would be interested in hearing your thoughts on the issue.

**Comment by Fullerpj** [comment]
I dont know why this would be happening with his/her mod but it might be something on his/her end and not the USAF mod

**Comment by Tibet4690** [comment]
I thought that could be the issue as well. However the desync occurs for every player using the above listed vehicles, all players also downloaded the latest USAF mod version via your mediafire link. As such I am of the opinion the issue isn't directly linked to one player's client.

I have reached out to the author of the werthles headless client script to see if he/she has any insight into the issue.

Note: I apparently over looked the F-16 last night for testing, testing it today it also appears to have desync issues well a HC is connected to the server. So here is an updated list of aircraft I am having issues with:
F-22
F-35A
C-17
B-2
F-16

Again the rest of the aircraft in you pack work alongside HCs without any issue. 

I'm going to extract the issue aircraft's pbos to see if they all share something in common that the non issue aircraft do not utilize. As you know the pack far more intimately than myself does anything come to mind?

**Comment by Fullerpj** [comment]
Nothing comes to mind that would cause an issue. If you find something let me know.

**Comment by Werthles** [comment]
Hi guys,
Tibet messaged me on the Steam Workshop. I am at a bit of a loss as to why certain aircraft would have this desync issue and not others. I'll try to run some tests with an older WHK version, or by spawning AIs on HCs the old fashioned way. I'll let you know if this is a WHK issue so this issue can be closed.

**Comment by Fullerpj** [comment]
Thanks Werthles ill be standing by

**Comment by Werthles** [comment]
We ran some tests. It looked like there was still a problem when there weren't HCs connected. There was still significant desync when we boarded just 4 planes. I've no idea why this would be, and I don't think I can help you further, sorry.

**Comment by Tibet4690** [comment]
Sorry for taking so long to reply to this. First I would like to thank Werthles for his time and willingness to join my server, even fighting through some compatibility hiccups. 

As Werthles said it now appears the issue is not related to headless clients, sorry I should have done more testing to confirm this. 

That aside there is something specific to these aircraft that is causing server desync... I'm far from an Arma mod expert and as such might not be aware of tools available to help test this. Perhaps there is some sort of server diagnostic I can run well testing the aircraft to better pinpoint the issue?

**Comment by Fullerpj** [comment]
I'm not sure. I run this and my clan server run the aircraft in question with no issues
