### ISSUE TITLE
Zeus Errors

### ISSUE THREAD

**Issue by Anoonki** [Fullerpj/United-States-Air-Force-Mod#61]
I have found myself unable to place certain objects in zeus, the Spirit, the F35 and all of the autonomous systems. Is there a reason for that? If this has been fixed in the most recent update, I'm sorry, I'm actually installing it now and if that's the case please say so and close this topic. IF there's some programming reason for that refer to the above apology and please explain so. During cooperative ops with a group, I have found myself attempting to use such aircraft and as I typically only put down some game logic for zeus and AGM and the like as well as the player units to keep the mission file small. I have found myself unable to actually use those aircraft during the ops which is a little disappointing.

**Comment by Fullerpj** [comment]
This issue has been resolved already. Please upate to the latest version
