### ISSUE TITLE
SEAD Missiles .5.3

### ISSUE THREAD

**Issue by TheRanger102** [Fullerpj/United-States-Air-Force-Mod#63]
Harms don't only go for Tigris AA tanks when using the SEAD menu that is in the F-35 and F-16. Also no boxes pop up to target Tigresses when the Harms are selected. This is with the play withsix version.

**Comment by Fullerpj** [comment]
Playwithsix version is not up to date. They messed up the download.

**Comment by TheRanger102** [comment]
Thought so, I just tried it with the manual hotfix download and it worked like a charm. Thanks for the quick reply and amazing mod by the way love every bit of it.
