### ISSUE TITLE
A-10 Arming menu.

### ISSUE THREAD

**Issue by irvnriir** [Fullerpj/United-States-Air-Force-Mod#65]
Please correct the A 10 loadout.
AIM-9s theoreticaly can be placed on both winds.
Add possibility to change hudra's on "Sniper RX" pod.
Fix AGM's 2->3.
In reality AGM's can be changed on all types of bombs 'MK's, JDAM's, GBU-12, CBU's, Mk-77'.
Add to weapon stations 4 and 8 all types of bombs and |1| AGM's.
Add to weapon station 6 Mk's.
Add MK-82 AIR and GBU-38 everywhere, where is MK-82.
Add to weapon stations 5 and 7 CBU-100and CBU 103.
Add to weapon stations 1 and 11 GBU 12.
Add external fuel tank's http://www.jetav8r.com/A10Gallery1/0370.jpg , http://alpaylas.com/resim/25022014145429-15.jpg .

![thunderbolt_laptop_background](https://cloud.githubusercontent.com/assets/13949704/9449932/819e4d6c-4aae-11e5-8df4-f0f14ed9dc23.jpg)
![a-10weaponsloadout1](https://cloud.githubusercontent.com/assets/13949704/9450448/4732d168-4ab1-11e5-8014-1b9ed89bb480.jpg)
![1000w_q75](https://cloud.githubusercontent.com/assets/13949704/9450286/7c8fae86-4ab0-11e5-9205-18dec5b64b5a.jpg)

**Comment by Fullerpj** [comment]
Ok your just being nit picky but I will explain why it's set up the way it is. PROXIES that is all thank you for your time.

**Comment by sargken** [comment]
+1 LoL
