### ISSUE TITLE
Issue: C17 para jump

### ISSUE THREAD

**Issue by LaocheXe** [Fullerpj/United-States-Air-Force-Mod#68]
Seems there is an issue, players get stuck inside the back of the C17 while trying to para jump out the two side doors or even the rear cargo ramp.

**Comment by Fullerpj** [comment]
We are working on why the side doors you can't jump out but open the rear bay all the way and you can jump out

**Comment by ghost** [comment]
Yea,Me too cant para jump out from the 2 jump doors and also the rear cargo T^T
