### ISSUE TITLE
F-35 Joint Strike Missile

### ISSUE THREAD

**Issue by TheRanger102** [Fullerpj/United-States-Air-Force-Mod#69]
Whenever you select the joint strike missile thought the service it won't load them onto the aircraft. I have tried to with just JAGM's and as well fully loaded. This is for hotfix 0.5.3.

**Comment by Fullerpj** [comment]
I will have a look at this when i get home. I havent had an issue with
loading the JSM into the aircraft.

**Comment by TheRanger102** [comment]
I have isolated the mod and it says that it is missing the JAGM_lancher. I have the playwithsix version and I have redownloaded it thought playwithsix and manual and still gives the same error.
