### ISSUE TITLE
Uniforms appear twice in Virtual Arsenal

### ISSUE THREAD

**Issue by Fourjays** [Fullerpj/United-States-Air-Force-Mod#73]
We've been using the USAF mod in our modpack and have noticed that all uniforms provided by the USAF mod appear twice in the Arsenal. For example, "Officer (2LT)", "Officer (MAJ)", "Officer (Green)", "Officer (Tan)". There are no discernable differences between the duplicates. Helmets, backpacks and vests are unaffected and appear only once.

I can reproduce this issue with just the USAF_SFS.pbo file loaded in Arma so no other mods appear to be in play here.

**Comment by Fullerpj** [comment]
ok thanks will fix
