### ISSUE TITLE
C130 no ACE interaction point

### ISSUE THREAD

**Issue by tebsu** [Fullerpj/United-States-Air-Force-Mod#77]
For parajump, we use the C130 but that one lacks an ACE interaction point so we cannot refuel it with ACE. I reported this issue to ACE and they said, its not their fault and didnt really help (https://github.com/acemod/ACE3/issues/3044#issuecomment-165544103). Maybe you can help us

**Comment by Fullerpj** [comment]
I am not sure what your doing wrong but you can definitely still load vehicles into the c-17. Refuel the c130 with refuel truck as normal

**Comment by sargken** [comment]
Hes talking about when using ACE and there new system to fuel and rearm with.

**Comment by Fullerpj** [comment]
Oh ok right now my mod doesn't support ACE. I've tried to contact them in regards to implementing ACE but no reply. I'm not going to chase them down for this either so when they respond I'll have ace added as long as it doesn't make a dependency

**Comment by sargken** [comment]
Ok sounds good. If i see they released some framework documentation for it i will send it your way. It shouldn't make it a dependency because they are only config values.

**Comment by tebsu** [comment]
Yea so i figured out, the loading script for the C17 works a bit different and thats why i renamed this issue.

**Comment by jokoho48** [comment]
@Fullerpj https://github.com/CBATeam/CBA_A3/wiki/Extended%20Eventhandlers#howto-guides
this you must basicly respect that ace interactions work
every special Feature are documentet here: http://ace3mod.com/wiki/framework/

**Comment by kymckay** [comment]
@Fullerpj Hey, if you need any help with this just reply to me on this issue, I'm not sure where you tried to contact us but as far as I'm aware we didn't know about it

**Comment by Fullerpj** [comment]
I tried contacting on the BI forums but yes I'd like to get my mod integrated with yours. Can you please add me on steam SGT Fuller that way we will have quick interaction rather than leaving messages.
