### ISSUE TITLE
A-10 Sound leaks into cockpit

### ISSUE THREAD

**Issue by Jacob-Tavcar** [Fullerpj/United-States-Air-Force-Mod#83]
every time i start the A-10 the engines are so insanely loud almost as if there is no cockpit canopy is there a way to correct this?

**Comment by Fullerpj** [comment]
This has already been fixed!

**Comment by Jacob-Tavcar** [comment]
It's weird because it hasent been fixed for me is there somewhere it could be getting messed up for me in the scripting somewhere ?

**Comment by Fullerpj** [comment]
I mean it will be out in the next update

**Comment by Jacob-Tavcar** [comment]
That's awesome thank you
