### ISSUE TITLE
HARM Targeting System (HTS) Pod

### ISSUE THREAD

**Issue by RaynorD** [Fullerpj/United-States-Air-Force-Mod#84]
Small feature request: It would be awesome if there were an HTS pod available for the right chin hardpoint, which would be required to use the SEAD system. I'm developing an advanced HARM attack display interface, which I would be happy to contribute to the mod if you're interested ([image](http://i.imgur.com/T7pWGlf.png)), and requiring an HTS pod would be perfect for it.

**Comment by Fullerpj** [comment]
Hey yes I would be willing to make this happen. May I ask one thing though?
that this HARM interface stays with USAF mod? and not go to firewill? USAF
mod is lacking right now and its hard to do it alone. If I had new content
I would definitely be willing.And would you be willing to make an adaption
for the F-35?

**Comment by RaynorD** [comment]
Yeah, it can be exclusive to you. It works on the F-35 now, which I don't think would require a pod since the systems are built in, but I can modify it as needed for the F-35 to match the more modern user interface or whatever. I'll PM you the mod in its current state on the forums and you can see what you think.

**Comment by Fullerpj** [comment]
Dude thanks so much!! Really making me get back in to Arma. So your a script writer?

**Comment by RaynorD** [comment]
Yeah, I'm a CS major, so I almost enjoy scripting Arma as much as playing it lol.

**Comment by Fullerpj** [comment]
Wanna help me get the mod back on its feet?

**Comment by RaynorD** [comment]
Yeah, I'd love to. The Cav uses these aircraft, so it would help out our fixed wing boys a lot.

**Comment by Fullerpj** [comment]
Excellent add me on steam
