### ISSUE TITLE
USAF Missilebox

### ISSUE THREAD

**Issue by TheNightstalk3r** [Fullerpj/United-States-Air-Force-Mod#87]
Detonating the missile box on the ground using zeus will create a very small destruction area. It won't go past any hills. Also in any case the smoke will stay in a radius of ~5m and stay on the ground unlike other mods where after the detonation an actual mushroom cloud grows. Is this not implemented or am I detonating it wrongly?

**Comment by Fullerpj** [comment]
What are you trying to detonate? the MOAB?

**Comment by TheNightstalk3r** [comment]
Yes, it's the moab I'm detonating. It's under others/missile_gltbox (or something like that)

**Comment by Fullerpj** [comment]
Ok ill have to take a look at it. So it blows up just doesn't go over
hills? Explain to me exactly what you see

**Comment by TheNightstalk3r** [comment]
So, when I detonate it, the shockwave won't go over a hill, so when it detonated vehicles and units on a hill even 50 m next to it won't be affected. Also the cloud won't gain height. It stays on the ground, 5-10m in diameter and 2-3 meter high

**Comment by TheNightstalk3r** [comment]
The cloud will even remain on the ground when the bomb is detonated in the air (same x position as the moab)

**Comment by Fullerpj** [comment]
Ok thanks ill take a look at it
