### ISSUE TITLE
c-5 Galaxy load positioning

### ISSUE THREAD

**Issue by Diesel486** [Fullerpj/United-States-Air-Force-Mod#92]
when loading vic's into c-5 they appear to sit on top of the craft. also when walking onto the crafts deck player floats, other times you cannot climb the ramp

![20161005060946_1](https://cloud.githubusercontent.com/assets/22622544/19086045/1f380ec2-8ac9-11e6-8e3d-5237c70b2949.jpg)
![20161005035336_1](https://cloud.githubusercontent.com/assets/22622544/19086053/2444ad26-8ac9-11e6-909f-131e377d6055.jpg)

**Comment by Fullerpj** [comment]
are these RHS vehicles?

**Comment by Diesel486** [comment]
yes they are. ill recheck but was sure it had the same affect with base game assets
Edit- base game vics are fine, though no paradrop. (unsure if its suppose to or not)

**Comment by Fullerpj** [comment]
RHS vehicles are not compatible with your version but it's been fixed already for new update

**Comment by Diesel486** [comment]
ok beauty. does the new update include vic paradrop from c-5/c-17?
