### ISSUE TITLE
USAF Not Working On My Server

### ISSUE THREAD

**Issue by JordannDev** [Fullerpj/United-States-Air-Force-Mod#95]
I have enabled the mod correctly, and installed it correctly, Although it does not seem to work everytime me and one of my friends join we get "Session Lost" even though we have installed it perfectly fine.

Any ideas?

**Comment by RaynorD** [comment]
Please upload your client rpt file (and if possible the server rpt too) to pastebin and link it here. It's the latest file in C:\Users\(user)\AppData\Local\Arma 3.
