### ISSUE TITLE
F-22 problem getting inside pilot's seat

### ISSUE THREAD

**Issue by FunkySmalls** [Fullerpj/United-States-Air-Force-Mod#96]
Hey everyone, I installed the USAF mod and for the most part it's great! Unfortunatly I'm having an issue with the F-22. I can't get inside it. If I spawn it through editor like how spawns you inside the seat that's the only way I can fly it but if I'm in a server or or spawn myself outside of it and try to get in it no matter where I go near the aircraft the option from scrolling through I can't find the option that would say, "Get in pilot's seat."  If anyone knows the fix not only me but my friends would greatly appreciate it, thanks!

**Comment by Sheppard85oc** [comment]
I have this same bug too. but i found a way to get in. 
I used the Enhanced Movement mod, i go on the wing look to the Pilotseat and get so in and can fly it. 
I think here its the same bug like the KC135

**Comment by hobart666** [comment]
Oh niiice, makes sense to me.
