### ISSUE TITLE
KC-135

### ISSUE THREAD

**Issue by coffee0398** [Fullerpj/United-States-Air-Force-Mod#98]
i can´t get into the aircraft

**Comment by coffee0398** [comment]
I need help please, in EDEN i put the aircraft, but when I get out of the aircraft then I can't get inside

**Comment by Sheppard85oc** [comment]
I have this bug too 
and here https://github.com/Fullerpj/United-States-Air-Force-Mod/issues/100

**Comment by Fullerpj** [comment]
It’s already fixed don’t need you to report anymore.

**Comment by hobart666** [comment]
Thanks for all the time you dedicate to this PJ, (definitely needs recognition, especially if you're still enlisted.)
