### ISSUE TITLE
Why not move to the workshop?

### ISSUE THREAD

**Issue by williamgiddings** [Fullerpj/United-States-Air-Force-Mod#99]
Allows for easy file patching, compatibility with other mods guaranteed (most of the time), more publicity, easier to receive feedback and not to mention the fact that no one uses Armaholic anymore.

**Comment by hobart666** [comment]
LoL thousands use armaholic daily. And even more use github...

**Comment by williamgiddings** [comment]
My apologies if what I said sounded spiteful. This is a great mod and I was just lazy to install it myself without Steam holding my hand :p
Didn't realize the Armaholic community was still this big! Keep up the great work!
